### ISSUE TITLE
scheduling BUG under linux-3.10.108

### ISSUE THREAD

**Issue by mgkiller7** [linux4wilc/driver#83] opened 2019-12-04 09:33 UTC
[151201.040000] BUG: scheduling while atomic: wpa_supplicant/1005/0x00000202 
[151201.040000] Modules linked in: wilc_sdio(C) 
[151201.050000] CPU: 0 PID: 1005 Comm: wpa_supplicant Tainted: G WC 3.10.108 #62 
[151201.050000] Backtrace: 
[151201.060000] [<c001128c>] (dump_backtrace+0x0/0x104) from [<c0011498>] (show_stack+0x18/0x1c) 
[151201.070000] r7:c1985178 r6:c152e000 r5:c1985178 r4:00000000 
[151201.070000] [<c0011480>] (show_stack+0x0/0x1c) from [<c0357a58>] (dump_stack+0x20/0x28) 
[151201.080000] [<c0357a38>] (dump_stack+0x0/0x28) from [<c003ffc0>] (__schedule_bug+0x48/0x60) 
[151201.090000] [<c003ff78>] (__schedule_bug+0x0/0x60) from [<c0359ab0>] (__schedule+0x60/0x3d0) 
[151201.100000] r5:c1985178 r4:c38d9b80 
[151201.100000] [<c0359a50>] (__schedule+0x0/0x3d0) from [<c0359ea8>] (schedule+0x88/0x8c) 
[151201.110000] [<c0359e20>] (schedule+0x0/0x8c) from [<c0358b6c>] (schedule_timeout+0x14c/0x170) 
[151201.120000] [<c0358a20>] (schedule_timeout+0x0/0x170) from [<c035a0a4>] (wait_for_common+0x100/0x1a4) 
[151201.130000] [<c0359fa4>] (wait_for_common+0x0/0x1a4) from [<c035a178>] (wait_for_completion_timeout+0x14/0x18) 
[151201.140000] r9:c152fd94 r8:00000008 r7:c37b4368 r6:c39023c0 r5:00000008 
r4:c37b42c0 
[151201.140000] [<c035a164>] (wait_for_completion_timeout+0x0/0x18) from [<bf00d318>] (cfg_set+0x100/0x144 [wilc_sdio]) 
[151201.150000] [<bf00d218>] (cfg_set+0x0/0x144 [wilc_sdio]) from [<bf00d630>] (wilc_send_config_pkt+0x1d8/0x240 [wilc_sdio]) 
[151201.160000] r9:bf018400 r8:00000001 r7:00000001 r6:c39023c0 r5:00000000 
r4:c152fd98 
[151201.160000] [<bf00d458>] (wilc_send_config_pkt+0x0/0x240 [wilc_sdio]) from [<bf00ab14>] (wilc_frame_register+0x94/0x114 [wilc_sdio]) 
[151201.170000] [<bf00aa80>] (wilc_frame_register+0x0/0x114 [wilc_sdio]) from [<bf0001b0>] (wilc_mgmt_frame_register+0xc0/0xd4 [wilc_sdio]) 
[151201.180000] r6:00000000 r5:000000d0 r4:c3902000 
[151201.180000] [<bf0000f0>] (wilc_mgmt_frame_register+0x0/0xd4 [wilc_sdio]) from [<c0323310>] (cfg80211_mlme_unregister_socket+0xc4/0xf0) 
[151201.190000] r8:c39033c0 r7:008003ed r6:c39033a8 r5:c37b4140 r4:c152bf40 
[151201.190000] [<c032324c>] (cfg80211_mlme_unregister_socket+0x0/0xf0) from [<c031e5d4>] (nl80211_netlink_notify+0xf4/0x10c) 
[151201.200000] [<c031e4e0>] (nl80211_netlink_notify+0x0/0x10c) from [<c003d890>] (notifier_call_chain+0x4c/0x70) 
[151201.210000] [<c003d844>] (notifier_call_chain+0x0/0x70) from [<c003da5c>] (__atomic_notifier_call_chain+0x40/0x54) 
[151201.220000] r9:c3cb65a0 r8:00000008 r7:ffffffff r6:c152fecc r5:00000001 
r4:c19c64fc 
[151201.230000] [<c003da1c>] (__atomic_notifier_call_chain+0x0/0x54) from [<c003da90>] (atomic_notifier_call_chain+0x20/0x28) 
[151201.240000] r7:c3cb65a0 r6:c3cb6580 r5:00000000 r4:c156b400 
[151201.250000] [<c003da70>] (atomic_notifier_call_chain+0x0/0x28) from [<c026e048>] (netlink_release+0x148/0x284) 
[151201.260000] [<c026df00>] (netlink_release+0x0/0x284) from [<c023c730>] (sock_release+0x28/0xa8) 
[151201.270000] r6:c3825470 r5:00000000 r4:c3cb6580 
[151201.270000] [<c023c708>] (sock_release+0x0/0xa8) from [<c023c7c4>] (sock_close+0x14/0x1c) 
[151201.280000] r5:c3cb34c8 r4:c141df00 
[151201.280000] [<c023c7b0>] (sock_close+0x0/0x1c) from [<c008fc48>] (__fput+0xfc/0x224) 
[151201.290000] [<c008fb4c>] (__fput+0x0/0x224) from [<c008fdb8>] (____fput+0x10/0x14) 
[151201.300000] [<c008fda8>] (____fput+0x0/0x14) from [<c00361a4>] (task_work_run+0x90/0xac) 
[151201.310000] [<c0036114>] (task_work_run+0x0/0xac) from [<c0010f70>] (do_work_pending+0xbc/0xc0) 
[151201.320000] r7:00000006 r6:c152ffb0 r5:c000e308 r4:c152e000 
[151201.320000] [<c0010eb4>] (do_work_pending+0x0/0xc0) from [<c000e1a4>] (work_pending+0xc/0x20) 
[151201.330000] r7:00000006 r6:00000002 r5:000cde70 r4:000cee28 
[151201.400000] wilc_sdio mmc0:0001:1 wlan0: INFO [debug_thread]*** Debug Thread Running *** 
[151201.460000] wilc_sdio mmc0:0001:1 wlan0: INFO [wilc_mgmt_frame_register]Frame registering Frame Type: d0: Boolean: 1

**Comment by AdhamAbozaeid** [comment] 2019-12-04 20:15
Duplicate of #50

**Closed by AdhamAbozaeid** 2019-12-04 20:15 UTC
